name: "Win 10"
on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: windows-latest
    env:
      SSS_DIR: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v2

      - name: bauen
        shell: cmd
        run: |
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat" x64
          bin/github_build_test.bat

      - name: testen
        shell: cmd
        run: |
            tests.exe
