name: "Win 10"
on:
  push:
    branches:
      - dev

env:
    SSS_DIR: ${{ github.workspace }}

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        compiler: [msvc-2019, msvc-2019]
        build-config: [Release, Debug]
        build-platform: [x64, x64]
        build-runtime: ["", /MT, /MD]

        include:
          - compiler: msvc-2019
            build-platform: x86
            os: windows-2019
            generator: Visual Studio 16 2019
            vc_vars:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat
          - compiler: msvc-2019
            build-platform: x64
            os: windows-2019
            generator: Visual Studio 16 2019
            vc_vars:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            extra_flags: -A Win64

    steps:
    - name: create build dir
      shell: cmd
      run: mkdir build

    - name: build
      shell: cmd
      working-directory: build
      env:
        INPUT_COMPILER: ${{ matrix.compiler }}
        INPUT_BUILD_CONFIG: ${{ matrix.build-config }}
        INPUT_EXTRA_FLAGS: ${{ matrix.extra_flags }}
        INPUT_BUILD_PLATFORM: ${{ matrix.build-platform }}
        INPUT_BUILD_RUNTIME: ${{ matrix.build-runtime }}
        INPUT_GENERATOR: ${{ matrix.generator }}
        VC_VARS: "${{ matrix.vc_vars }}"
      run: |
        "%VC_VARS%"
        set compiler_flags=-fp:fast -fp:except- -EHsc -Gm- -GR- -EHa- -Zo -Oi -WX -W4 -wd4201 -wd4100 -wd4101 -wd4189 -wd4505 -wd4127 -wd4702 -wd4530 -wd4800 -FC -Z7 -I../src
        set linker_flags= -incremental:no -opt:ref user32.lib gdi32.lib winmm.lib Shlwapi.lib Ws2_32.lib
        cl %compiler_flags% ..\tests\tests.cpp -Fetests.exe /link %linker_flags%
        if %ERRORLEVEL% NEQ 0 (
            echo "fehler bei der kompilierung des projekts"
            exit /b %ERRORLEVEL%
        )

    - name: run
      shell: cmd
      working-directory: build
      run: |
          echo %CD%
          tests.exe
